"""
Read and validate a compiled ITCHI event.

This example consumes an event file generated by:

    python examples/smoke_test_synthetic.py \
      --output-path outputs/events/smoke_test_synthetic.nc

The goal is to validate the exported NetCDF/Zarr file without recomputing
ITCHI from scratch.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import xarray as xr

from itchi.io import read_dataset

REQUIRED_VARIABLES: tuple[str, ...] = (
    "ITCHI",
    "ITCHI_max",
    "ITCHI_acc",
)


def assert_required_variables(dataset: xr.Dataset) -> None:
    """
    Validate that required ITCHI variables are present.
    """
    missing = [name for name in REQUIRED_VARIABLES if name not in dataset]

    if missing:
        missing_text = ", ".join(missing)
        raise KeyError(f"Missing required ITCHI variable(s): {missing_text}")


def assert_unit_interval(name: str, values: xr.DataArray) -> None:
    """
    Validate that an ITCHI field remains within [0, 1].
    """
    min_value = float(values.min(skipna=True))
    max_value = float(values.max(skipna=True))

    if min_value < 0.0 or max_value > 1.0:
        raise ValueError(
            f"{name} is outside [0, 1]. " f"Observed min={min_value}, max={max_value}."
        )


def summarize_dataset(dataset: xr.Dataset) -> None:
    """
    Print a compact summary of the compiled event dataset.
    """
    print("Compiled ITCHI event loaded successfully.\n")

    print("Dimensions:")
    for name, size in dataset.sizes.items():
        print(f"  {name}: {size}")

    print("\nVariables:")
    for name in dataset.data_vars:
        dims = dataset[name].dims
        shape = dataset[name].shape
        print(f"  {name}: dims={dims}, shape={shape}")

    print("\nGlobal attributes:")
    for key, value in dataset.attrs.items():
        if key == "snapshot_metadata_json":
            print(f"  {key}: <serialized metadata>")
        else:
            print(f"  {key}: {value}")

    if "snapshot_metadata_json" in dataset.attrs:
        metadata = json.loads(dataset.attrs["snapshot_metadata_json"])
        print("\nSnapshot metadata:")
        for item in metadata:
            print(f"  {item}")


def validate_compiled_event(dataset: xr.Dataset) -> None:
    """
    Run basic structural and physical checks on the compiled event.
    """
    assert_required_variables(dataset)

    for variable in REQUIRED_VARIABLES:
        assert_unit_interval(variable, dataset[variable])

    if "time" not in dataset["ITCHI"].dims:
        raise ValueError("ITCHI must include a temporal dimension named 'time'.")

    if dataset["ITCHI_max"].dims == dataset["ITCHI"].dims:
        raise ValueError("ITCHI_max should be an event product without time dimension.")

    if dataset["ITCHI_acc"].dims == dataset["ITCHI"].dims:
        raise ValueError("ITCHI_acc should be an event product without time dimension.")


def plot_compiled_event(
    dataset: xr.Dataset,
    output_path: Path | None = None,
) -> None:
    """
    Plot diagnostic fields from a compiled ITCHI event.
    """
    itchi_first = dataset["ITCHI"].isel(time=0)
    itchi_max = dataset["ITCHI_max"]
    itchi_acc = dataset["ITCHI_acc"]

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(13, 4),
        constrained_layout=True,
    )

    fields = [
        (itchi_first, "ITCHI first snapshot"),
        (itchi_max, "ITCHI_max"),
        (itchi_acc, "ITCHI_acc"),
    ]

    for ax, (field, title) in zip(axes, fields, strict=False):
        image = ax.pcolormesh(field.values, shading="auto")
        ax.set_title(title)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        fig.colorbar(image, ax=ax)

    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, dpi=150)
        print(f"\nSaved figure: {output_path}")

    plt.show()


def run_read_example(
    input_path: str,
    make_plot: bool = False,
    figure_path: str | None = None,
) -> None:
    """
    Read, validate and optionally plot a compiled ITCHI event.
    """
    dataset = read_dataset(input_path)

    try:
        summarize_dataset(dataset)
        validate_compiled_event(dataset)

        print("\nCompiled ITCHI event validation passed.")

        if make_plot:
            output_path = Path(figure_path) if figure_path is not None else None
            plot_compiled_event(
                dataset=dataset,
                output_path=output_path,
            )

    finally:
        dataset.close()


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Read and validate a compiled ITCHI event.",
    )

    parser.add_argument(
        "--input-path",
        type=str,
        default="outputs/events/smoke_test_synthetic.nc",
        help="Path to compiled ITCHI event NetCDF or Zarr file.",
    )

    parser.add_argument(
        "--plot",
        action="store_true",
        help="Show diagnostic plots.",
    )

    parser.add_argument(
        "--figure-path",
        type=str,
        default=None,
        help="Optional path to save diagnostic figure.",
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    run_read_example(
        input_path=args.input_path,
        make_plot=args.plot,
        figure_path=args.figure_path,
    )
